### PR TITLE
Fix #123 performance bottlenecks

### LINKED ISSUE #123: Performance bottlenecks
**Describe the bug**
Performance bottlenecks exit in GetSymDefAt() and GetSymDefCount(). Several collection access methods use inefficient searches.

**To Reproduce**
1.	Load a large MVR file with 1000+ objects of mixed types (symbols).
2.	Call GetSymDefAt() in a loop.
3.	Observe significant performance degradation as collection size increases.

**Expected behavior**
•	Large datasets should be handled efficiently without performance degradation.

### PR DESCRIPTION
**Pull request by adragnevVW**
Fix for #123:

Changes:
Improving GetSymDefAt() and GetSymDefCount()
Adding a check if the symbol contains other symbol as a child.

### CODE REVIEW

**Review by ILane-VW — APPROVED** [review]

**Comment by adragnevVW** [comment]
Hi @AndriiVoitenko,
Do you think this change must be submitted?

**Review by ILane-VW — CHANGES_REQUESTED** [review]
see changes from Andrii

File: src/SceneDataExchange.cpp [hunk 1]
```diff
@@ -2880,7 +2886,9 @@ SceneDataExchange::~SceneDataExchange()
 	{
 		fFilesInZip[i]->DeleteOnDisk();
 	}
-	
+
+	fSymDefObjs.clear();
+	fClassObjs.clear();
```
Comment (AndriiVoitenko) [inline src/SceneDataExchange.cpp:2891]: Have you try to run reading from MVR file several times in a row? I can not find where you clear  fMappingDefinitionObjs

File: src/SceneDataExchange.cpp [hunk 2]
```diff
@@ -2990,6 +3002,7 @@ SceneDataSymDefObjPtr SceneDataExchange::ReadSymDefObject(const IXMLFileNodePtr&
 	newSymDef->ReadFromNode(node, this);
 	
 	fAuxDataObjs.push_back(newSymDef);
+	fSymDefObjs.push_back( newSymDef );
```
[the remark this answers is not in the document]
Comment (AndriiVoitenko) [reply src/SceneDataExchange.cpp:3001]: It still comes in both and all other objects coming also in 2 arrays

**Review by AndriiVoitenko — CHANGES_REQUESTED** [review]

**Comment by adragnevVW** [comment]
Hi @AndriiVoitenko ,
Thanks for the suggestions!

File: src/SceneDataExchange.h [hunk 3]
```diff
@@ -976,9 +978,11 @@ namespace SceneData
 		SceneDataProviderObjArray			fProviderObjs;
 		SceneDataAuxObjArray				fAuxDataObjs;
```
Comment (AndriiVoitenko) [inline src/SceneDataExchange.h]: Do you still use it? It looks like you removed all pushes into fAuxDataObjs, but you still have it in definitions.

File: src/SceneDataExchange.cpp [hunk 4]
```diff
@@ -3656,6 +3676,21 @@ bool SceneDataExchange::WriteXml(const IFolderIdentifierPtr& folder, IXMLFileIOB
 					{
 						auxObj->PrintToFile(pAuxDataNode, this);
 					}
```
Comment (AndriiVoitenko) [inline src/SceneDataExchange.cpp]: Is fAuxDataObjs always empty?

**Review by AndriiVoitenko — CHANGES_REQUESTED** [review]

**Review by AndriiVoitenko — CHANGES_REQUESTED** [review]
check comments

**Review by AndriiVoitenko — APPROVED** [review]

**Review by ILane-VW — APPROVED** [review]
